### ISSUE TITLE
Fails to run custom build command with latest Erlang

### ISSUE THREAD

**Issue by cgregfreeman** [goertzenator/erlang_nif-sys#28] opened 2017-06-12 00:09 UTC
After updating to Erlang/OTP 20 [RELEASE CANDIDATE 2], this dependency fails to build

```
   Compiling void v1.0.2
   Compiling quote v0.3.15
   Compiling unicode-xid v0.0.4
   Compiling erlang_nif-sys v0.6.1
   Compiling lazy_static v0.1.16
   Compiling synom v0.11.3
   Compiling lazy_static v0.2.8
   Compiling unreachable v0.1.1
   Compiling syn v0.11.11
error: failed to run custom build command for `erlang_nif-sys v0.6.1`
process didn't exit successfully: `../debug/build/erlang_nif-sys-06da930bd64b6054/build-script-build` (exit code: 101)
--- stdout
Unsupported Erlang version.

Is the erlang_nif-sys version up to date in the Cargo.toml?
Does 'cargo update' fix it?
If not please report at https://github.com/goertzenator/erlang_nif-sys.

--- stderr
thread 'main' panicked at 'gen_api.erl encountered an error.'../.cargo/registry/src/github.com-1ecc6299db9ec823/erlang_nif-sys-0.6.1/build.rs:28
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build failed, waiting for other jobs to finish...
error: build failed
** (RuntimeError) Rust NIF compile error (rustc exit code 101)
    lib/mix/tasks/compile.rustler.ex:58: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    lib/mix/tasks/compile.rustler.ex:12: Mix.Tasks.Compile.Rustler.run/1
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/tasks/compile.all.ex:19: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:37: Mix.Tasks.Compile.All.with_logger_app/1
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3

```

**Comment by goertzenator** [comment] 2017-06-17 14:25
Duplicate of #27.

**Closed by goertzenator** 2017-06-17 14:25 UTC
Labels: duplicate
